using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.SqlClient;
using System.IO;

/*
Author(s) : Gerald Frilot Prateek Gurnani
ULID(s) : C00060678 / C00124478
Assignment: assignment-11
Azure Website: https://portal.azure.com/?Microsoft_Azure_
Education_correlationId=ad9e8021-8f98-47ba-96a2-e971604ff035#blade/Microsoft_Azure_Education/EducationMenuBlade/quickstart
Due Date:  4/29/2019 @ 11:55 pm
Description: Design two applications (One builds a database schema and the other processes the database)
Certification of Authenticity :
            We certify that the code and other required components in the files of this project, other than code
            provided by the instructor or in the instructions for this assignment or generated by Visual
            Studio is entirely our own work.
 */
namespace project_11
{
    class Program
    { 

        SqlConnection thisConnection ;
        SqlCommand thisCommand ;
        SqlDataReader thisReader ;
        static string[] myarray = {"Select a city for viewing: \n",
       "1 ========== Baton Rogue\n","2 ========== Kenner\n","3 ========== Lafayette\n","4 ========== Lake Charles\n",
        "5 ========== New Orleans\n","6 ========== Shreveport\n"};

    static void Main(string[] args)
        {new Program();}

        // Method: ConnectToDatabase
        // Description: Contains a string of login parameters to connect to the database. 
        // Passes the string to the Connection, opens the connection, and creates a command.
        public void ConnectToDatabase()
        {
            string connectString = "Server=tcp:medserver1.database.windows.net,1433;Initial Catalog=project11;" +
            "Persist Security Info=False;User ID=projectMed;Password=Medical123;MultipleActiveResultSets=False;" +
            "Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
            thisConnection = new SqlConnection(connectString);
            thisConnection.Open();
            thisCommand = thisConnection.CreateCommand();
        }

        // Method:  Upload
        // Description: Provides option for user input and returns a medical query of information.

        public void Upload()
        {
            string choice = "";

            Console.WriteLine("********************************Select from the following: ******************************************\n");
            Console.WriteLine("1 - Population of a chosen city year (2015 or 2016).");
            Console.WriteLine("2 - Values, with confidence levels and category, for a chosen measure about a chosen city in a given year..");
            Console.WriteLine("3 - Average value for a chosen measure about a chosen city in a given year...");
            Console.WriteLine("4 - Average value for a chosen measure about all cities in a given year....");
            Console.WriteLine("5 - Longitude and latitude pairs for the samples taken for a chosen city in a given year.....");

                while (choice != "1" && choice != "2" && choice != "3" && choice != "4" && choice != "5")
                {
                    choice = Console.ReadLine();
                    if (choice != "1" && choice != "2" && choice != "3" && choice != "4" && choice != "5")
                    {
                        Console.WriteLine("Try Again!");
                    }
                }

            switch (choice)
            {

                case "1":
                    string choiceb = "";
                    Console.WriteLine("Select a year => Enter '15' for 2015 or '16' for 2016");
                    while (choiceb != "15" && choiceb != "16")
                    {
                            choiceb = Console.ReadLine();
                            if (choiceb != "15" && choiceb != "16")
                            {
                                Console.WriteLine("Try Again!");
                            }
                    }

                    int choiceb2 = Int32.Parse(choiceb);
                        switch (choiceb2)
                        {
                            case 15:
                                try
                                {
                                    thisCommand.CommandText = "SELECT * FROM HealthData WHERE year = '15'";
                                    thisReader = thisCommand.ExecuteReader();

                                    while (thisReader.Read())
                                    {

                                        Console.WriteLine("\t{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}", thisReader[0], thisReader[1],
                                            thisReader[2],thisReader[3], thisReader[4],thisReader[5], thisReader[6], thisReader[7],
                                            thisReader[8],thisReader[9]);
                                    }
                                
                                }
                                catch (SqlException e)
                                {
                                    Console.WriteLine(e.Message);
                                }
                                Console.WriteLine("\n\t\t\tPress enter to quit:");
                                Console.ReadKey();
                                break;

                            case 16:
                                try
                                {
                                    thisCommand.CommandText = "SELECT * FROM HealthData WHERE year = '16'";
                                    thisReader = thisCommand.ExecuteReader();

                                    while (thisReader.Read())
                                    {
                                        Console.WriteLine("\t{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}", thisReader[0], thisReader[1],
                                            thisReader[2], thisReader[3], thisReader[4], thisReader[5], thisReader[6], thisReader[7], 
                                            thisReader[8], thisReader[9]);
                                    }       
                                }
                                catch (SqlException e)
                                {
                                    Console.WriteLine(e.Message+'\n');
                                }
                                 Console.WriteLine("\n\t\t\tPress enter to quit:");
                                 Console.ReadKey();
                                 break;
                        }
                        break;
                case "2":
                        Console.WriteLine("Select a year for viewing :Enter '15' for 2015 and '16' for 2016");
                        string choicec = "";
                        while (choicec != "15" && choicec != "16")
                        {
                            choicec = Console.ReadLine();
                            if (choicec != "15" && choicec != "16")
                            {
                                Console.WriteLine("Try Again!");
                            }
                        }
                    Console.WriteLine(myarray[0]+myarray[1]+myarray[2]+myarray[3]+myarray[4]+myarray[5]+myarray[6]);
                        string choiced = "";
                        while (choiced != "1" && choiced != "2" && choiced != "3" && choiced != "4" && choiced != "5" && choiced != "6")
                        {
                            choiced = Console.ReadLine();
                        if (choiced != "1" && choiced != "2" && choiced != "3" && choiced != "4" && choiced != "5" && choiced != "6")
                        {
                            Console.WriteLine(choiced);
                            Console.WriteLine("Select an integer from  1 - 6");
                        }
                        
                        }

                        try
                        {
                            string tempString = "SELECT lowconf, hiconf, category FROM HealthData WHERE year = @year AND city = @city";
                            thisCommand = new SqlCommand(tempString, thisConnection);
                            thisCommand.Parameters.AddWithValue("@year", choicec);
                            thisCommand.Parameters.AddWithValue("@city", choiced);
                            thisReader = thisCommand.ExecuteReader();

                            while (thisReader.Read())
                            {
                                string myCity = thisReader[1].ToString();
                                string myYear = thisReader[0].ToString();
                                Console.WriteLine("\t{0}\t{1}\t{2}", thisReader[0], thisReader[1], thisReader[2]);
                            }
                        }
                        catch (SqlException e)
                        {
                            Console.WriteLine(e.Message);
                            
                        }
                        Console.WriteLine("\n\t\t\t\tPress enter to quit:");
                        Console.ReadKey();

                        break;
                    case "3":
                        Console.WriteLine("Select a year for viewing :  Enter '15' for 2015 and '16' for 2016");
                        string choicee = "";
                        while (choicee != "15" && choicee != "16")
                        {
                            choicee = Console.ReadLine();
                            if (choicee != "15" && choicee != "16")
                            {
                                Console.WriteLine("Try again!");
                            }
                        }
                    Console.WriteLine(myarray[0] + myarray[1] + myarray[2] + myarray[3] + myarray[4] + myarray[5] + myarray[6]);
                    string choicef = "";
                        while (choicef != "1" && choicef != "2" && choicef != "3" && choicef != "4" && choicef != "5" && choicef != "6")
                        {
                            choicef = Console.ReadLine();
                            if (choicef != "1" && choicef != "2" && choicef != "3" && choicef != "4" && choicef != "5" && choicef != "6")
                            {
                                Console.WriteLine("Please enter an integer 1 - 6");
                            }
                        }
                        try
                        {
                            string tempString = "SELECT AVG(measure) FROM HealthData WHERE year = @year AND city = @city";
                            thisCommand = new SqlCommand(tempString, thisConnection);
                            thisCommand.Parameters.AddWithValue("@year", choicee);
                            thisCommand.Parameters.AddWithValue("@city", choicef);
                            thisReader = thisCommand.ExecuteReader();

                            while (thisReader.Read())
                            {
                                Console.WriteLine("Measure: ");
                                Console.WriteLine("\t{0}", thisReader[0]);
                                Console.ReadKey();
                            }
                        }
                        catch (SqlException e)
                        {
                            Console.WriteLine(e.Message);
                            
                        }
                        break;
                    case "4":
                        Console.WriteLine("Select a year:  Enter '15' for 2015 and '16' for 2016");
                        string choiceg = "";
                        while (choiceg != "15" && choiceg != "16")
                        {
                            choiceg = Console.ReadLine();
                            if (choiceg != "15" && choiceg != "16")
                            {
                                Console.WriteLine("Select 15 or 16 please!");
                            }
                        }
                        try
                        {
                            string tempString = "SELECT AVG(measure) FROM HealthData WHERE year = @year";
                            thisCommand = new SqlCommand(tempString, thisConnection);
                            thisCommand.Parameters.AddWithValue("@year", choiceg);
                            thisReader = thisCommand.ExecuteReader();

                            while (thisReader.Read())
                            {
                                Console.WriteLine("Measure: ");
                                Console.WriteLine("\t{0}", thisReader[0]);
                               
                            }
                            Console.WriteLine("\n\t\t\t\tPress enter to quit:");
                            Console.ReadKey();
                        }
                        catch (SqlException e)
                        {
                            Console.WriteLine(e.Message);
                        }
                        break;
                    case "5":
                        Console.WriteLine("Select a year: Enter '15' for 2015 and '16' for 2016");
                        string choiceh = "";
                        while (choiceh != "15" && choiceh != "16")
                        {
                            choiceh = Console.ReadLine();
                            if (choiceh != "15" && choiceh != "16")
                            {
                                Console.WriteLine("Select 15 or 16 please!");
                            }
                        }
                    Console.WriteLine(myarray[0] + myarray[1] + myarray[2] + myarray[3] + myarray[4] + myarray[5] + myarray[6]);
                    string choicei = "";
                        while (choicei != "1" && choicei != "2" && choicei != "3" && choicei != "4" && choicei != "5" && 
                        choicei != "6")
                        {
                            choicei = Console.ReadLine();
                            if (choicei != "1" && choicei != "2" && choicei != "3" && choicei != "4" && choicei != "5" && choicei != "6")
                            {
                                Console.WriteLine("Please enter an integer 1 - 6");
                            }
                        }
                        try
                        {
                            string tempString = "SELECT latitude, longitude FROM HealthData WHERE year = @year AND city = @city";
                            thisCommand = new SqlCommand(tempString, thisConnection);
                            thisCommand.Parameters.AddWithValue("@year", choiceh);
                            thisCommand.Parameters.AddWithValue("@city", choicei);
                            thisReader = thisCommand.ExecuteReader();

                            while (thisReader.Read())
                            {

                                Console.WriteLine("\t{0}\t{1}", thisReader[0], thisReader[1]);
                                
                            }
                        
                        }
                        catch (SqlException e)
                        {
                            Console.WriteLine(e.Message);
                        }
                        Console.WriteLine("\n\t\t\t\tPress enter to quit:");
                        Console.ReadKey();
                        break;
            }
            thisConnection.Close();
        }

        // Constructor: Program
        // Connects to the database and then prompts the user for input.

            public Program()
            {
            try
            {
                ConnectToDatabase();
            }
            catch (SqlException e)
            {
              Console.WriteLine(e.Message);
              return;
            }
            Upload();
            }
    }
}
    

